package-lock.json, package.json, src/App.js, src/index.js
=> [DONE] [SWA-8] Santa Cruz Map

src/Components/Filter.js, src/Components/styles.module.css
https://saveourspecies.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=SWA&modal=detail&selectedIssue=SWA-22
I accidentally called it SOS instead of SWA :(
Made the filter bar more aesthetically pleasing/appropriate for what we want to do
=> [DONE][SOS-22] Add a filter bar

package-lock.json, package.json, public/index.html, src/App.css, src/App.js, src/Components/Filter.js, src/Components/Map.js
- Outsource searching and filtering to Algolia
- Use Algolia widgets for Filter UI
=> [WIP][SWA-52] Renew filter design with Algolia widgets

src/Components/Legend.js, src/Components/LegendStyles.css, src/Components/Map.js
Initial commit to reflect current state of map
=> Legend for the map icons

src/Components/ClusteredMarkers.js, src/Components/Filter.js, src/Components/Legend.js, src/Components/MarkerSVG.js, src/Components/NavMenu.js
Pair programmed with Aziz to refactor/reword some stuff with SVG and navbar
=> Refactor SVG to a component and reword navbar

package-lock.json, package.json, src/Components/About.css, src/Components/About.js, src/Components/NavMenu.js
=> About page

src/Components/UploadPopup.js
Change Legend names so that the species are categorized like so:
**Otariids**: sea lions, 
**Phocids**: seals,
**Odontocetes**: dolphins & whales
=> [WIP][SWA-173] Update legend names to their correct scientific categories

functions/src/index.ts, src/Components/UploadPopup.js
When a new record is uploaded to the database, Firebase generates a unique identifier for it server-side. Instead of this unique ID we'd like to upload records with a specified id using the National Database Number.
https://firebase.google.com/docs/database/rest/save-data
=> [WIP][SWA-188] Set unique identifier of new records to National Database Number when uploading 

functions/src/index.ts
=> [SWA-189] Fix databaseOnCreate issue

src/Components/UploadPopup.js
=> [SWA-191] Fix upload with no longitude bug

src/Components/Sidebar.css, src/Components/UploadPopup.css, src/Components/UploadPopup.js, src/api.js, src/index.js
Add a upload progress bar to the upload popup
=> [SWA-194] Display Upload Progress

src/Components/Footer.css, src/Components/Map.js, src/Components/Sidebar.css
=> Fix map height

src/Components/StrandingPopup.css, src/Components/StrandingPopup.js
Change identifying marker of strandings from date to national database number
=> Change popup id

src/Components/UploadPopup.js
=> Fix upload bug for Windows machines

src/Components/UploadPopup.js
=> Fix newline bug

src/Components/UploadPopup.js
=> Empty column fix

src/Components/UploadPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-18
=> [LSM-18] Fix parsing of longitude when parsing CSV data

src/Components/ClusteredMarkers.js, src/Components/StrandingPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-15
=> [LSM-15] Change popup to show on hover instead of click

src/Components/StrandingPopup.css, src/Components/StrandingPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-19
=> [LSM-19] Fix popup being cut off at 100% zoom level

src/Components/StrandingPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-20
=> [LSM-20] Clean up formatting of fields in popup

src/Components/Filter.js, src/Components/Map.js, src/Components/Sidebar.js, src/Components/StrandingPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-23
=> [LSM-23] Upload updated 2020 and 2021 data

src/Components/StrandingPopup.css, src/Components/StrandingPopup.js, src/Components/UploadPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-30
=> [LSM-30] Skip uploading records that don't have Longitude and/or Latitude

src/Components/StrandingPopup.css, src/Components/StrandingPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-4
=> [LSM-4] Implement expanded case study popup

package-lock.json, src/Components/StrandingPopup.css, src/Components/StrandingPopup.js
Changed the longitude/latitude to locality details. Changed the way the popup decides on its height and changed the paddings and some text size to fit everything into the current popup size, along with slightly increasing the popup width.
=> [LSM-22] Replace "Latitude" and "Longitude" in popup with "Locality Detail"

src/Components/UploadPopup.css, src/Components/UploadPopup.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-32
=> [LSM-32] Check for missing Latitude/Longitude and Year of Examination fields when uploading records

src/App.js, src/Components/CaseStudyPage.css, src/Components/CaseStudyPage.js, src/Components/NavMenu.js, src/Components/StrandingPopup.css, src/Components/StrandingPopup.js, src/api.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-24
=> [LSM-24] Implement separate case study page

src/Components/About.js, src/Components/Footer.js
https://lmlstrandingmap.atlassian.net/jira/software/projects/LSM/boards/1?selectedIssue=LSM-33
=> [LSM-33] Update About page and Footer

src/Components/CaseStudyPopup.css, src/Components/CaseStudyPopup.js, src/Components/Map.js, src/Components/StrandingPopup.css, src/Components/StrandingPopup.js
Moved case study popup from StrandingPopup.js into its own component in CaseStudyPopup.js to clean up the code a bit
=> Refactored case study popup into its own component
